
export const sampleEmployees = [
    {
        id: '1',
        fullName: 'Sarah Chen',
        email: 'sarah.chen@company.com',
        jobTitle: 'Chief Technology Officer',
        department: 'Engineering',
        location: 'San Francisco, CA',
        phone: '+1 (555) 123-4567',
        status: 'Active',
        hireDate: '2020-01-15',
    },
    {
        id: '2',
        fullName: 'Marcus Johnson',
        email: 'marcus.johnson@company.com',
        jobTitle: 'Senior Product Manager',
        department: 'Product',
        location: 'New York, NY',
        phone: '+1 (555) 234-5678',
        status: 'Active',
        hireDate: '2021-03-22',
    },
    {
        id: '3',
        fullName: 'Emily Rodriguez',
        email: 'emily.rodriguez@company.com',
        jobTitle: 'Lead Designer',
        department: 'Design',
        location: 'Remote',
        phone: '+1 (555) 345-6789',
        status: 'Remote',
        hireDate: '2021-06-10',
    },
    {
        id: '4',
        fullName: 'David Kim',
        email: 'david.kim@company.com',
        jobTitle: 'Software Engineer',
        department: 'Engineering',
        location: 'San Francisco, CA',
        phone: '+1 (555) 456-7890',
        status: 'Active',
        hireDate: '2022-02-01',
    },
    {
        id: '5',
        fullName: 'Jessica Taylor',
        email: 'jessica.taylor@company.com',
        jobTitle: 'Marketing Director',
        department: 'Marketing',
        location: 'Austin, TX',
        phone: '+1 (555) 567-8901',
        status: 'Active',
        hireDate: '2020-08-15',
    },
    {
        id: '6',
        fullName: 'Michael Brown',
        email: 'michael.brown@company.com',
        jobTitle: 'Sales Manager',
        department: 'Sales',
        location: 'Chicago, IL',
        phone: '+1 (555) 678-9012',
        status: 'Active',
        hireDate: '2021-11-30',
    },
    {
        id: '7',
        fullName: 'Aisha Patel',
        email: 'aisha.patel@company.com',
        jobTitle: 'HR Manager',
        department: 'Human Resources',
        location: 'New York, NY',
        phone: '+1 (555) 789-0123',
        status: 'Active',
        hireDate: '2020-05-20',
    },
    {
        id: '8',
        fullName: 'James Wilson',
        email: 'james.wilson@company.com',
        jobTitle: 'DevOps Engineer',
        department: 'Engineering',
        location: 'Seattle, WA',
        phone: '+1 (555) 890-1234',
        status: 'Active',
        hireDate: '2022-07-12',
    },
    {
        id: '9',
        fullName: 'Olivia Martinez',
        email: 'olivia.martinez@company.com',
        jobTitle: 'UX Researcher',
        department: 'Design',
        location: 'Remote',
        phone: '+1 (555) 901-2345',
        status: 'Remote',
        hireDate: '2022-09-05',
    },
    {
        id: '10',
        fullName: 'Robert Anderson',
        email: 'robert.anderson@company.com',
        jobTitle: 'Finance Manager',
        department: 'Finance',
        location: 'New York, NY',
        phone: '+1 (555) 012-3456',
        status: 'Active',
        hireDate: '2019-12-01',
    },
    {
        id: '11',
        fullName: 'Sophia Lee',
        email: 'sophia.lee@company.com',
        jobTitle: 'Content Strategist',
        department: 'Marketing',
        location: 'Los Angeles, CA',
        phone: '+1 (555) 123-5678',
        status: 'Active',
        hireDate: '2023-01-10',
    },
    {
        id: '12',
        fullName: 'Daniel Garcia',
        email: 'daniel.garcia@company.com',
        jobTitle: 'Senior Software Engineer',
        department: 'Engineering',
        location: 'San Francisco, CA',
        phone: '+1 (555) 234-6789',
        status: 'Active',
        hireDate: '2021-04-18',
    },
    {
        id: '13',
        fullName: 'Isabella Thomas',
        email: 'isabella.thomas@company.com',
        jobTitle: 'Customer Success Lead',
        department: 'Customer Support',
        location: 'Boston, MA',
        phone: '+1 (555) 345-7890',
        status: 'Active',
        hireDate: '2022-03-25',
    },
    {
        id: '14',
        fullName: 'Christopher White',
        email: 'christopher.white@company.com',
        jobTitle: 'Data Analyst',
        department: 'Analytics',
        location: 'Remote',
        phone: '+1 (555) 456-8901',
        status: 'Remote',
        hireDate: '2022-11-08',
    },
    {
        id: '15',
        fullName: 'Mia Jackson',
        email: 'mia.jackson@company.com',
        jobTitle: 'Product Designer',
        department: 'Design',
        location: 'Austin, TX',
        phone: '+1 (555) 567-9012',
        status: 'On Leave',
        hireDate: '2021-09-15',
    },
];
